AVAILABLE_COUNTRIES = [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bhutan",
    "bolivia",
    "bosnia and herzegovina",
    "botswana",
    "brazil",
    "british virgin islands",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "cayman islands",
    "central african republic",
    "chile",
    "china",
    "chinese taipei",
    "colombia",
    "costa rica",
    "croatia",
    "cuba",
    "cyprus",
    "czech republic",
    "denmark",
    "djibouti",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "england",
    "equatorial guinea",
    "estonia",
    "ethiopia",
    "faroe islands",
    "fiji",
    "finland",
    "france",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guyana",
    "haiti",
    "honduras",
    "hong kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle of man",
    "israel",
    "italy",
    "ivory coast",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macau",
    "madagascar",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "mauritania",
    "mauritius",
    "mexico",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "nigeria",
    "north macedonia",
    "norway",
    "oman",
    "pakistan",
    "palestine",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "puerto rico",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "saint lucia",
    "san marino",
    "saudi arabia",
    "scotland",
    "senegal",
    "serbia",
    "singapore",
    "slovakia",
    "slovenia",
    "south africa",
    "south korea",
    "spain",
    "sri lanka",
    "sweden",
    "switzerland",
    "syria",
    "tajikistan",
    "tanzania",
    "thailand",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "uzbekistan",
    "venezuela",
    "vietnam",
    "wales",
    "yemen",
    "zambia",
    "zimbabwe",
]

COUNTRY_FLAGS = {
    "afghanistan": "🇦🇫",
    "albania": "🇦🇱",
    "algeria": "🇩🇿",
    "andorra": "🇦🇩",
    "angola": "🇦🇴",
    "antigua and barbuda": "🇦🇬",
    "argentina": "🇦🇷",
    "armenia": "🇦🇲",
    "aruba": "🇦🇼",
    "australia": "🇦🇺",
    "austria": "🇦🇹",
    "azerbaijan": "🇦🇿",
    "bahamas": "🇧🇸",
    "bahrain": "🇧🇭",
    "bangladesh": "🇧🇩",
    "barbados": "🇧🇧",
    "belarus": "🇧🇾",
    "belgium": "🇧🇪",
    "belize": "🇧🇿",
    "benin": "🇧🇯",
    "bhutan": "🇧🇹",
    "bolivia": "🇧🇴",
    "bosnia and herzegovina": "🇧🇦",
    "botswana": "🇧🇼",
    "brazil": "🇧🇷",
    "british virgin islands": "🇻🇬",
    "brunei": "🇧🇳",
    "bulgaria": "🇧🇬",
    "burkina faso": "🇧🇫",
    "burundi": "🇧🇮",
    "cambodia": "🇰🇭",
    "cameroon": "🇨🇲",
    "canada": "🇨🇦",
    "cape verde": "🇨🇻",
    "cayman islands": "🇰🇾",
    "central african republic": "🇨🇫",
    "chile": "🇨🇱",
    "china": "🇨🇳",
    "chinese taipei": "🇹🇼",
    "colombia": "🇨🇴",
    "costa rica": "🇨🇷",
    "croatia": "🇭🇷",
    "cuba": "🇨🇺",
    "cyprus": "🇨🇾",
    "czech republic": "🇨🇿",
    "denmark": "🇩🇰",
    "djibouti": "🇩🇯",
    "dominican republic": "🇩🇴",
    "ecuador": "🇪🇨",
    "egypt": "🇪🇬",
    "el salvador": "🇸🇻",
    "england": "🏴",
    "equatorial guinea": "🇬🇶",
    "estonia": "🇪🇪",
    "ethiopia": "🇪🇹",
    "faroe islands": "🇫🇴",
    "fiji": "🇫🇯",
    "finland": "🇫🇮",
    "france": "🇫🇷",
    "gabon": "🇬🇦",
    "gambia": "🇬🇲",
    "georgia": "🇬🇪",
    "germany": "🇩🇪",
    "ghana": "🇬🇭",
    "greece": "🇬🇷",
    "guam": "🇬🇺",
    "guatemala": "🇬🇹",
    "guernsey": "🇬🇬",
    "guinea": "🇬🇳",
    "guyana": "🇬🇾",
    "haiti": "🇭🇹",
    "honduras": "🇭🇳",
    "hong kong": "🇭🇰",
    "hungary": "🇭🇺",
    "iceland": "🇮🇸",
    "india": "🇮🇳",
    "indonesia": "🇮🇩",
    "iran": "🇮🇷",
    "iraq": "🇮🇶",
    "ireland": "🇮🇪",
    "isle of man": "🇮🇲",
    "israel": "🇮🇱",
    "italy": "🇮🇹",
    "ivory coast": "🇨🇮",
    "jamaica": "🇯🇲",
    "japan": "🇯🇵",
    "jersey": "🇯🇪",
    "jordan": "🇯🇴",
    "kazakhstan": "🇰🇿",
    "kenya": "🇰🇪",
    "kosovo": "🇽🇰",
    "kuwait": "🇰🇼",
    "kyrgyzstan": "🇰🇬",
    "laos": "🇱🇦",
    "latvia": "🇱🇻",
    "lebanon": "🇱🇧",
    "libya": "🇱🇾",
    "liechtenstein": "🇱🇮",
    "lithuania": "🇱🇹",
    "luxembourg": "🇱🇺",
    "macau": "🇲🇴",
    "madagascar": "🇲🇬",
    "malaysia": "🇲🇾",
    "maldives": "🇲🇻",
    "mali": "🇲🇱",
    "malta": "🇲🇹",
    "mauritania": "🇲🇷",
    "mauritius": "🇲🇺",
    "mexico": "🇲🇽",
    "moldova": "🇲🇩",
    "monaco": "🇲🇨",
    "mongolia": "🇲🇳",
    "montenegro": "🇲🇪",
    "morocco": "🇲🇦",
    "mozambique": "🇲🇿",
    "myanmar": "🇲🇲",
    "namibia": "🇳🇦",
    "nepal": "🇳🇵",
    "netherlands": "🇳🇱",
    "new zealand": "🇳🇿",
    "nicaragua": "🇳🇮",
    "nigeria": "🇳🇬",
    "north macedonia": "🇲🇰",
    "norway": "🇳🇴",
    "oman": "🇴🇲",
    "pakistan": "🇵🇰",
    "palestine": "🇵🇸",
    "panama": "🇵🇦",
    "papua new guinea": "🇵🇬",
    "paraguay": "🇵🇾",
    "peru": "🇵🇪",
    "philippines": "🇵🇭",
    "poland": "🇵🇱",
    "portugal": "🇵🇹",
    "puerto rico": "🇵🇷",
    "qatar": "🇶🇦",
    "romania": "🇷🇴",
    "russia": "🇷🇺",
    "rwanda": "🇷🇼",
    "saint lucia": "🇱🇨",
    "san marino": "🇸🇲",
    "saudi arabia": "🇸🇦",
    "scotland": "🏴",
    "senegal": "🇸🇳",
    "serbia": "🇷🇸",
    "singapore": "🇸🇬",
    "slovakia": "🇸🇰",
    "slovenia": "🇸🇮",
    "south africa": "🇿🇦",
    "south korea": "🇰🇷",
    "spain": "🇪🇸",
    "sri lanka": "🇱🇰",
    "sweden": "🇸🇪",
    "switzerland": "🇨🇭",
    "syria": "🇸🇾",
    "tajikistan": "🇹🇯",
    "tanzania": "🇹🇿",
    "thailand": "🇹🇭",
    "trinidad and tobago": "🇹🇹",
    "tunisia": "🇹🇳",
    "turkey": "🇹🇷",
    "turkmenistan": "🇹🇲",
    "uganda": "🇺🇬",
    "ukraine": "🇺🇦",
    "united arab emirates": "🇦🇪",
    "united kingdom": "🇬🇧",
    "united states": "🇺🇸",
    "uruguay": "🇺🇾",
    "uzbekistan": "🇺🇿",
    "venezuela": "🇻🇪",
    "vietnam": "🇻🇳",
    "wales": "🏴",
    "yemen": "🇾🇪",
    "zambia": "🇿🇲",
    "zimbabwe": "🇿🇼",
}


def format_country_name(country: str) -> str:
    return " ".join(word.capitalize() for word in country.split())


def get_country_flag(country: str) -> str:
    return COUNTRY_FLAGS.get(country.lower(), "🌍")


def format_country_label(country: str) -> str:
    normalized = country.strip().lower()
    flag = get_country_flag(normalized)
    name = format_country_name(normalized)
    return f"{flag} {name}"